package org.uksrc.archive.searchrequest.service;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.persistence.TypedQuery;
import jakarta.persistence.criteria.*;
import org.ivoa.dm.caom2.Observation;
import org.uksrc.archive.searchrequest.descriptors.*;
import org.uksrc.archive.searchrequest.query.QueryContext;
import org.uksrc.archive.searchrequest.schema.ObservationSearchRequest;

import java.util.List;

/**
 * Service class responsible for constructing search queries for
 *  observations based on various filtering criteria.
 * <p>
 * This class defines a configurable set of search parameters that can be
 * applied dynamically to filter observation data. The search parameters are
 * represented by implementations of the SearchParameter interface, which
 * encapsulate specific filtering logic.
 * <p>
 * Responsibilities of this class include:
 * - Managing a list of predefined search parameters, each designed to handle
 *   a specific aspect of observation filtering (e.g. target, energy band, start date).
 * - Constructing a dynamic query using the Java Persistence API (JPA) Criteria API
 *   to ensure type-safe and flexible query generation.
 * - Combining predicates generated by active search parameters into a unified query filter.
 * <p>
 * Key Components:
 * - EntityManager: Used to create and execute JPA TypedQuery instances.
 * - Search Parameters: A static list of parameter implementations that contribute
 *   filter conditions based on the input ObservationSearchRequest.
 * - QueryContext: An intermediary container that holds query-related components
 *   such as CriteriaBuilder, Root, and a collection of predicates.
 * <p>
 * The `searchQuery` method is the entry point for this service. It processes an
 * `ObservationSearchRequest` by applying the active search parameters to construct
 * a type-safe query. The resulting `TypedQuery` can then be used to fetch observations
 * that match the specified criteria.
 */
@ApplicationScoped
public class ObservationSearchService {

    @Inject
    EntityManager em;

    private final List<SearchParameter> parameters = List.of(
            new TargetParameter(),
            new BandParameter(),
            new StartDateParameter(),
            new ProjectName()
    );

    /**
     * Constructs a JPA TypedQuery for fetching Observation entities based on the
     * filtering criteria specified in the given ObservationSearchRequest.
     * The query dynamically applies the search parameters to build predicates
     * and combines them to form the final query.
     *
     * @param request the ObservationSearchRequest containing filtering criteria
     *                such as target, band, and startDate. If a criterion is not
     *                provided, it will not be applied to the query.
     * @return a TypedQuery for Observation entities, pre-configured with the
     *         filtering conditions derived from the request.
     */
    public TypedQuery<Observation> searchQuery(ObservationSearchRequest request) {
        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Observation> cq = cb.createQuery(Observation.class);
        Root<Observation> root = cq.from(Observation.class);

        cq.distinct(true);

        QueryContext ctx = new QueryContext(cb, root);

        for (SearchParameter parameter : parameters) {
            parameter.applyIfPresent(request, ctx);
        }

        cq.where(ctx.predicates().toArray(new Predicate[0]));

        return em.createQuery(cq);
    }
}

